version: '2'

services:
  jboss-datagrid:
    container_name: ${CONTAINER_NAME_JBOSS_DATAGRID}
    build: ./jboss-datagrid
    image: jboss/datagrid:${JBOSS_DATAGRID_VERSION}
    ports:
      - "8180:8080" 
      - "10090:9990"
      - "11222:11222"
    networks:
      - default
  jboss-eap:
    container_name: ${CONTAINER_NAME_JBOSS_EAP}
    build: ./jboss-eap-${JBOSS_EAP_VERSION}
    image: jboss/eap:${JBOSS_EAP_VERSION}
    volumes:
      - /home/ihsan/Documents/docker/docker-redhat-jboss/jboss-eap-${JBOSS_EAP_VERSION}/deploy:/opt/jboss/jboss-eap/deploy
    ports:
      - "8280:8080" 
      - "10190:9990"
    networks:
      - default
  jboss-datavirtualization:
    container_name: ${CONTAINER_NAME_JBOSS_DATAVIRTUALIZATION}
    build: ./jboss-datavirtualization
    image: jboss/datavirtualization:${JBOSS_DATAVIRTUALIZATION_VERSION}
    ports:
      - "8380:8080" 
      - "10290:9990"
    networks:
      - default
  jboss-fuse:
    container_name: ${CONTAINER_NAME_JBOSS_FUSE}
    build: ./jboss-fuse
    image: jboss/fuse:${JBOSS_FUSE_VERSION}
    volumes:
      - /home/ihsan/Documents/docker/docker-redhat-jboss/jboss-fuse/deploy:/opt/jboss/jboss-fuse/deploy
    ports:
      - "8181:8181"
      - "8101:8101" 
      - "1099:1099" 
      - "8161:8161"
      - "44444:44444" 
      - "61616:61616"
    networks:
      - default
  jboss-fuse-7.0.1:
    container_name: jboss-fuse-7.0.1
    build: ./jboss-fuse-7.0.1
    image: jboss/fuse:7.0.1
    volumes:
      - /home/ihsan/Documents/docker/docker-redhat-jboss/jboss-fuse-7.0.1/deploy:/opt/jboss/jboss-fuse/deploy
    links:
      - jboss-eap
      - jboss-datagrid
    ports:
      - "8181:8181"
      - "8101:8101"
      - "8161:8161" 
      - "1099:1099" 
      - "44444:44444" 
      - "61616:61616"
    networks:
      - default
  wildfly:
    container_name: ${CONTAINER_NAME_WILDFLY}
    build: ./wildfly
    image: jboss/wildfly:${WILDFLY_VERSION}
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - default