version: '2'

services:
  jboss-eap:
    container_name: ${CONTAINER_NAME_JBOSS_EAP}
    build: ./jboss-eap-${JBOSS_EAP_VERSION}
    image: jboss/eap:${JBOSS_EAP_VERSION}
    ports:
      - "8280:8080" 
      - "10190:9990"
    networks:
      - default
  jboss-fuse:
    container_name: ${CONTAINER_NAME_JBOSS_FUSE}
    build: ./jboss-fuse
    image: jboss/fuse:${JBOSS_FUSE_VERSION}
    ports:
      - "8181:8181"
      - "8101:8101" 
      - "1099:1099" 
      - "44444:44444" 
      - "61616:61616"
    networks:
      - default
  wildfly:
    container_name: ${CONTAINER_NAME_WILDFLY}
    build: ./wildfly
    image: jboss/wildfly:${WILDFLY_VERSION}
    ports:
      - "8080:8080"
      - "9990:9990"
    networks:
      - default